import dp_final_of_ibrl_dataset_anomaly_detection_humidity as dphu
import dp_final_of_ibrl_dataset_anomaly_detection_temp as dptemp
import final_of_ibrl_dataset_anomaly_detection_humidity as hu
import final_of_ibrl_dataset_anomaly_detection_temp as temp

dphu
dptemp
hu
temp
